# Generated by Django 4.2.7 on 2024-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
