# Generated by Django 4.2.7 on 2024-02-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='timestamp',
        ),
    ]
