# Generated by Django 4.2.7 on 2024-02-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_repayment',
        ),
    ]
