# Generated by Django 4.2.7 on 2024-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_loan_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan_repayment',
            field=models.BooleanField(default=False),
        ),
    ]
