# Generated by Django 4.2.7 on 2024-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_loan_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Receive', 'Receive'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer'), ('Loan', 'Loan'), ('Repayment', 'Repayment')], max_length=20, null=True),
        ),
    ]
